# Generated by Django 2.1.3 on 2019-01-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('soltero', 'Solter@'), ('casado', 'Casad@'), ('viudo', 'Viud@'), ('divorciado', 'Divorciad@'), ('unionLibre', 'Unión Libre')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipoCuenta',
            field=models.CharField(choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorro')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Depósito')], default='', max_length=30),
        ),
    ]
